/* import the fontawesome core */
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faAngleDoubleDown,
  faAngleDoubleUp,
  faArrowDown,
  faAt,
  faCalendarDay,
  faCamera,
  faCheck,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  faClipboardList,
  faClock,
  faCloud,
  faCloudMeatball,
  faCog,
  faComment,
  faCompass,
  faCompressArrowsAlt,
  faDraftingCompass,
  faEdit,
  faExchangeAlt,
  faExclamationTriangle,
  faFan,
  faFileDownload,
  faFileInvoice,
  faHistory,
  faInfinity,
  faKey,
  faLongArrowAltLeft,
  faLongArrowAltRight,
  faMapMarkerAlt,
  faMedal,
  faMousePointer,
  faPaperPlane,
  faPaperclip,
  faPlus,
  faSignOut,
  faSignIn,
  faSignature,
  faSitemap,
  faSmog,
  faSort,
  faSortDown,
  faSortUp,
  faTape,
  faThermometerEmpty,
  faThermometerFull,
  faTimes,
  faTrash,
  faUser,
  faUserPlus,
  faSearch,
} from "@fortawesome/free-solid-svg-icons";

import {
  faFacebookF,
  faTwitter,
  faInstagram,
  faLinkedinIn,
} from "@fortawesome/free-brands-svg-icons";

import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

library.add(
  faFacebookF,
  faTwitter,
  faInstagram,
  faLinkedinIn,
  faAngleDoubleDown,
  faAngleDoubleUp,
  faArrowDown,
  faAt,
  faSearch,
  faCalendarDay,
  faCamera,
  faCheck,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  faClipboardList,
  faClock,
  faCloud,
  faCloudMeatball,
  faCog,
  faComment,
  faCompass,
  faCompressArrowsAlt,
  faDraftingCompass,
  faEdit,
  faExchangeAlt,
  faExclamationTriangle,
  faFan,
  faFileDownload,
  faFileInvoice,
  faHistory,
  faInfinity,
  faKey,
  faLongArrowAltLeft,
  faLongArrowAltRight,
  faMapMarkerAlt,
  faMedal,
  faMousePointer,
  faPaperPlane,
  faPaperclip,
  faPlus,
  faSignIn,
  faSignOut,
  faSignature,
  faSitemap,
  faSmog,
  faSort,
  faSortDown,
  faSortUp,
  faTape,
  faThermometerEmpty,
  faThermometerFull,
  faTimes,
  faTrash,
  faUser,
  faUserPlus
);

export default FontAwesomeIcon;
